In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [3]:
path='/content/drive/MyDrive/nagapatinam/facial_emotions/Training'

In [ ]:
%matplotlib inline
import math
import numpy as np
import matplotlib.pyplot as plt
import os

from skimage import measure
from skimage.color import rgb2gray
from skimage.util import img_as_ubyte
from skimage import io
from skimage.feature import greycomatrix, greycoprops

In [ ]:
imgList = os.listdir('/content/drive/MyDrive/nagapatinam/facial_emotions/Training')

In [ ]:
imgPath = []
for path in imgList:
    pathImg = f'/content/drive/MyDrive/nagapatinam/facial_emotions/Training/{path}'
    imgPath.append(pathImg)
imgPath.sort()

In [ ]:
from skimage.feature import graycomatrix, graycoprops
ax = []
ay = []
az = []
aa = []
ab = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale

    glcm = graycomatrix(image, distances=[4], angles=[0], levels=256)
    ax.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    ay.append(graycoprops(glcm, 'correlation')[0, 0])
    az.append(graycoprops(glcm, 'homogeneity')[0, 0])
    aa.append(graycoprops(glcm, 'contrast')[0, 0])
    ab.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
#  4.18879, 2.35619, 3.92699, 1.74533, 3.49066, 5.23599, 5.93412
bx = []
by = []
bz = []
ba = []
bb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[0.785398], levels=256)
    bx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    by.append(graycoprops(glcm, 'correlation')[0, 0])
    bz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ba.append(graycoprops(glcm, 'contrast')[0, 0])
    bb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
cx = []
cy = []
cz = []
ca = []
cb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[1.0472], levels=256)
    cx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    cy.append(graycoprops(glcm, 'correlation')[0, 0])
    cz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ca.append(graycoprops(glcm, 'contrast')[0, 0])
    cb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
dx = []
dy = []
dz = []
da = []
db = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[2.0944], levels=256)
    dx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    dy.append(graycoprops(glcm, 'correlation')[0, 0])
    dz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    da.append(graycoprops(glcm, 'contrast')[0, 0])
    db.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
ex = []
ey = []
ez = []
ea = []
eb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[3.14159], levels=256)
    ex.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    ey.append(graycoprops(glcm, 'correlation')[0, 0])
    ez.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ea.append(graycoprops(glcm, 'contrast')[0, 0])
    eb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
fx = []
fy = []
fz = []
fa = []
fb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[4.18879], levels=256)
    fx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    fy.append(graycoprops(glcm, 'correlation')[0, 0])
    fz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    fa.append(graycoprops(glcm, 'contrast')[0, 0])
    fb.append(graycoprops(glcm, 'energy')[0, 0])


In [4]:
import pandas as pd

In [6]:
imgName = os.listdir('/content/drive/MyDrive/nagapatinam/facial_emotions/Training')
imgName.sort()

NameError: name 'os' is not defined

In [ ]:
submission = pd.DataFrame(dict(label=0, image_name=imgName, ax=ax, ay=ay, az=az, aa=aa, ab=ab, bx=bx, by=by, bz=bz, ba=ba, bb=bb, cx=cx, cy=cy, cz=cz, ca=ca, cb=cb, dx=dx, dy=dy, dz=dz, da=da, db=db,  ex=ex, ey=ey, ez=ez, ea=ea, eb=eb, fx=fx, fy=fy,fz=fz, fa=fa, fb=fb  ))


In [ ]:
submission.rename(columns = {0: "image_name", 1: "label"}, inplace = True)

In [ ]:
submission = submission.sort_values('image_name')
submission.to_csv('submission.csv', index=False)
submission.head()

label     image_name         ax        ay        az           aa        ab  \
0      0    Angry-1.jpg  32.696023  0.640132  0.044584  1965.876894  0.023646   
1      0   Angry-10.jpg  35.511837  0.568112  0.025650  2048.322443  0.022904   
2      0  Angry-100.jpg  38.374527  0.381174  0.027387  2502.427557  0.022924   
3      0   Angry-11.jpg  28.971591  0.428590  0.045800  1787.282197  0.024438   
4      0   Angry-12.jpg  39.513731  0.317501  0.027621  2937.013731  0.023060   

          bx        by        bz  ...         ex        ey        ez  \
0  33.275062  0.615360  0.043705  ...  32.696023  0.640132  0.044584   
1  37.485926  0.472948  0.037008  ...  35.511837  0.568112  0.025650   
2  35.261728  0.456777  0.033205  ...  38.374527  0.381174  0.027387   
3  31.000988  0.322132  0.054840  ...  28.971591  0.428590  0.045800   
4  35.338272  0.476322  0.035968  ...  39.513731  0.317501  0.027621   

            ea        eb         fx        fy        fz           fa        fb  
0  1965.876894  0.023646  31.811111  0.645717  0.043477  1927.430435  0.024116  
1  2048.322443  0.022904  32.453140  0.581045  0.041420  1995.272464  0.023429  
2  2502.427557  0.022924  30.924155  0.562133  0.034143  1819.919324  0.023429  
3  1787.282197  0.024438  28.212077  0.432007  0.064775  1818.639130  0.025204  
4  2937.013731  0.023060  30.021256  0.627465  0.048822  1647.213527  0.023647  

[5 rows x 32 columns]

In [ ]:
path1='/content/drive/MyDrive/nagapatinam/facial_emotions/Testing'

In [ ]:
imgList1= os.listdir('/content/drive/MyDrive/nagapatinam/facial_emotions/Testing')

In [ ]:
imgPath1 = []
for path1 in imgList1:
    pathImg1 = f'/content/drive/MyDrive/nagapatinam/facial_emotions/Testing/{path1}'
    imgPath1.append(pathImg1)
imgPath1.sort()

In [ ]:
from skimage.feature import graycomatrix, graycoprops
hx = []
hy = []
hz = []
ha = []
hb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale

    glcm = graycomatrix(image, distances=[4], angles=[0], levels=256)
    hx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    hy.append(graycoprops(glcm, 'correlation')[0, 0])
    hz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ha.append(graycoprops(glcm, 'contrast')[0, 0])
    hb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
#  4.18879, 2.35619, 3.92699, 1.74533, 3.49066, 5.23599, 5.93412
nx = []
ny = []
nz = []
na = []
nb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[0.785398], levels=256)
    nx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    ny.append(graycoprops(glcm, 'correlation')[0, 0])
    nz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    na.append(graycoprops(glcm, 'contrast')[0, 0])
    nb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
ix = []
iy = []
iz = []
ia = []
ib = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[1.0472], levels=256)
    ix.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    iy.append(graycoprops(glcm, 'correlation')[0, 0])
    iz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ia.append(graycoprops(glcm, 'contrast')[0, 0])
    ib.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
jx = []
jy = []
jz = []
ja = []
jb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[2.0944], levels=256)
    jx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    jy.append(graycoprops(glcm, 'correlation')[0, 0])
    jz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ja.append(graycoprops(glcm, 'contrast')[0, 0])
    jb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
kx = []
ky = []
kz = []
ka = []
kb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[3.14159], levels=256)
    kx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    ky.append(graycoprops(glcm, 'correlation')[0, 0])
    kz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    ka.append(graycoprops(glcm, 'contrast')[0, 0])
    kb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
lx = []
ly = []
lz = []
la = []
lb = []
for patch in imgPath:
    image_rgb = io.imread(patch)

    # Check if the image is grayscale
    if len(image_rgb.shape) == 2:  # Grayscale image
        image = img_as_ubyte(image_rgb)  # No need to convert to grayscale
    else:  # RGB image
        image = img_as_ubyte(rgb2gray(image_rgb))  # Convert to grayscale


    glcm = graycomatrix(image, distances=[4], angles=[4.18879], levels=256)
    lx.append(graycoprops(glcm, 'dissimilarity')[0, 0])
    ly.append(graycoprops(glcm, 'correlation')[0, 0])
    lz.append(graycoprops(glcm, 'homogeneity')[0, 0])
    la.append(graycoprops(glcm, 'contrast')[0, 0])
    lb.append(graycoprops(glcm, 'energy')[0, 0])


In [ ]:
imgName = os.listdir('/content/drive/MyDrive/nagapatinam/facial_emotions/Testing')
imgName.sort()

In [ ]:
submission1 = pd.DataFrame(dict(label=1,image_name=imgName, hx=hx, hy=hy, hz=hz, ha=ha, hb=hb, nx=nx, ny=ny, nz=nz, na=na, nb=nb, ix=ix, iy=iy, iz=iz, ia=ia, ib=ib, jx=jx, jy=jy, jz=jz, ja=ja, jb=jb,  kx=kx, ky=ky, kz=kz, ka=ka, kb=kb, lx=lx, ly=ly,lz=lz, la=la, lb=lb ))


In [ ]:
submission1.rename(columns = {0: "image_name", 1: "label"}, inplace = True)

In [ ]:
submission1.head()

label     image_name         hx        hy        hz           ha        hb  \
0      1    Angry-1.jpg  32.696023  0.640132  0.044584  1965.876894  0.023646   
1      1   Angry-10.jpg  35.511837  0.568112  0.025650  2048.322443  0.022904   
2      1  Angry-100.jpg  38.374527  0.381174  0.027387  2502.427557  0.022924   
3      1   Angry-11.jpg  28.971591  0.428590  0.045800  1787.282197  0.024438   
4      1   Angry-12.jpg  39.513731  0.317501  0.027621  2937.013731  0.023060   

          nx        ny        nz  ...         kx        ky        kz  \
0  33.275062  0.615360  0.043705  ...  32.696023  0.640132  0.044584   
1  37.485926  0.472948  0.037008  ...  35.511837  0.568112  0.025650   
2  35.261728  0.456777  0.033205  ...  38.374527  0.381174  0.027387   
3  31.000988  0.322132  0.054840  ...  28.971591  0.428590  0.045800   
4  35.338272  0.476322  0.035968  ...  39.513731  0.317501  0.027621   

            ka        kb         lx        ly        lz           la        lb  
0  1965.876894  0.023646  31.811111  0.645717  0.043477  1927.430435  0.024116  
1  2048.322443  0.022904  32.453140  0.581045  0.041420  1995.272464  0.023429  
2  2502.427557  0.022924  30.924155  0.562133  0.034143  1819.919324  0.023429  
3  1787.282197  0.024438  28.212077  0.432007  0.064775  1818.639130  0.025204  
4  2937.013731  0.023060  30.021256  0.627465  0.048822  1647.213527  0.023647  

[5 rows x 32 columns]

In [ ]:
submission1 = submission1.sort_values('image_name')
submission1.to_csv('submission1.csv', index=False)
submission1.head()

label     image_name         hx        hy        hz           ha        hb  \
0      1    Angry-1.jpg  32.696023  0.640132  0.044584  1965.876894  0.023646   
1      1   Angry-10.jpg  35.511837  0.568112  0.025650  2048.322443  0.022904   
2      1  Angry-100.jpg  38.374527  0.381174  0.027387  2502.427557  0.022924   
3      1   Angry-11.jpg  28.971591  0.428590  0.045800  1787.282197  0.024438   
4      1   Angry-12.jpg  39.513731  0.317501  0.027621  2937.013731  0.023060   

          nx        ny        nz  ...         kx        ky        kz  \
0  33.275062  0.615360  0.043705  ...  32.696023  0.640132  0.044584   
1  37.485926  0.472948  0.037008  ...  35.511837  0.568112  0.025650   
2  35.261728  0.456777  0.033205  ...  38.374527  0.381174  0.027387   
3  31.000988  0.322132  0.054840  ...  28.971591  0.428590  0.045800   
4  35.338272  0.476322  0.035968  ...  39.513731  0.317501  0.027621   

            ka        kb         lx        ly        lz           la        lb  
0  1965.876894  0.023646  31.811111  0.645717  0.043477  1927.430435  0.024116  
1  2048.322443  0.022904  32.453140  0.581045  0.041420  1995.272464  0.023429  
2  2502.427557  0.022924  30.924155  0.562133  0.034143  1819.919324  0.023429  
3  1787.282197  0.024438  28.212077  0.432007  0.064775  1818.639130  0.025204  
4  2937.013731  0.023060  30.021256  0.627465  0.048822  1647.213527  0.023647  

[5 rows x 32 columns]

In [ ]:
df = pd.DataFrame(submission)
df = df.append(pd.DataFrame(submission1), ignore_index=True)


<ipython-input-71-97bcf039b097>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame(submission1), ignore_index=True)


In [ ]:
df.rename(columns = {0: "image_names", 1: "label"}, inplace = True)

In [ ]:
df.to_csv('features.csv', index=False)

In [ ]:
df.head(1300)

label     image_name         ax        ay        az           aa  \
0         0    Angry-1.jpg  32.696023  0.640132  0.044584  1965.876894   
1         0   Angry-10.jpg  35.511837  0.568112  0.025650  2048.322443   
2         0  Angry-100.jpg  38.374527  0.381174  0.027387  2502.427557   
3         0   Angry-11.jpg  28.971591  0.428590  0.045800  1787.282197   
4         0   Angry-12.jpg  39.513731  0.317501  0.027621  2937.013731   
...     ...            ...        ...       ...       ...          ...   
1295      1   Happy-12.jpg        NaN       NaN       NaN          NaN   
1296      1  Happy-120.jpg        NaN       NaN       NaN          NaN   
1297      1  Happy-121.jpg        NaN       NaN       NaN          NaN   
1298      1  Happy-122.jpg        NaN       NaN       NaN          NaN   
1299      1  Happy-123.jpg        NaN       NaN       NaN          NaN   

            ab         bx        by        bz  ...         kx        ky  \
0     0.023646  33.275062  0.615360  0.043705  ...        NaN       NaN   
1     0.022904  37.485926  0.472948  0.037008  ...        NaN       NaN   
2     0.022924  35.261728  0.456777  0.033205  ...        NaN       NaN   
3     0.024438  31.000988  0.322132  0.054840  ...        NaN       NaN   
4     0.023060  35.338272  0.476322  0.035968  ...        NaN       NaN   
...        ...        ...       ...       ...  ...        ...       ...   
1295       NaN        NaN       NaN       NaN  ...  32.023201  0.617029   
1296       NaN        NaN       NaN       NaN  ...  22.977273  0.508368   
1297       NaN        NaN       NaN       NaN  ...  29.788826  0.638383   
1298       NaN        NaN       NaN       NaN  ...  24.527936  0.481642   
1299       NaN        NaN       NaN       NaN  ...  34.208807  0.501341   

            kz           ka        kb         lx        ly        lz  \
0          NaN          NaN       NaN        NaN       NaN       NaN   
1          NaN          NaN       NaN        NaN       NaN       NaN   
2          NaN          NaN       NaN        NaN       NaN       NaN   
3          NaN          NaN       NaN        NaN       NaN       NaN   
4          NaN          NaN       NaN        NaN       NaN       NaN   
...        ...          ...       ...        ...       ...       ...   
1295  0.053987  2167.250473  0.024721  32.830918  0.589083  0.058066   
1296  0.049072   900.452652  0.024273  20.703382  0.581061  0.057804   
1297  0.098007  1885.174242  0.028785  27.524638  0.654691  0.095542   
1298  0.051409  1539.522254  0.025480  21.563285  0.684198  0.056688   
1299  0.031795  2285.330019  0.023398  37.817874  0.366502  0.035410   

               la        lb  
0             NaN       NaN  
1             NaN       NaN  
2             NaN       NaN  
3             NaN       NaN  
4             NaN       NaN  
...           ...       ...  
1295  2261.810628  0.026706  
1296   770.454106  0.025121  
1297  1819.459903  0.029991  
1298   918.519807  0.025581  
1299  2845.999517  0.023617  

[1300 rows x 62 columns]

In [ ]:
df.shape

(2082, 62)

In [ ]:
df=df.replace(np.nan,0)

In [ ]:
df.head(10)

label     image_name         ax        ay        az           aa        ab  \
0      0    Angry-1.jpg  32.696023  0.640132  0.044584  1965.876894  0.023646   
1      0   Angry-10.jpg  35.511837  0.568112  0.025650  2048.322443  0.022904   
2      0  Angry-100.jpg  38.374527  0.381174  0.027387  2502.427557  0.022924   
3      0   Angry-11.jpg  28.971591  0.428590  0.045800  1787.282197  0.024438   
4      0   Angry-12.jpg  39.513731  0.317501  0.027621  2937.013731  0.023060   
5      0   Angry-13.jpg  44.271780  0.564206  0.152616  4554.532197  0.106145   
6      0   Angry-14.jpg  38.786458  0.476572  0.024580  2535.563920  0.022786   
7      0   Angry-15.jpg  53.098011  0.440058  0.022148  5113.082860  0.022529   
8      0   Angry-16.jpg  45.958807  0.407496  0.039583  4522.910511  0.023891   
9      0   Angry-17.jpg  47.490057  0.516004  0.093458  4580.943655  0.060938   

          bx        by        bz  ...   kx   ky   kz   ka   kb   lx   ly   lz  \
0  33.275062  0.615360  0.043705  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  37.485926  0.472948  0.037008  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  35.261728  0.456777  0.033205  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  31.000988  0.322132  0.054840  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  35.338272  0.476322  0.035968  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5  45.869136  0.539933  0.164521  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6  35.040988  0.572179  0.027839  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7  43.222716  0.616951  0.030780  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
8  53.063704  0.257795  0.030735  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
9  43.873086  0.569247  0.101403  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    la   lb  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  
5  0.0  0.0  
6  0.0  0.0  
7  0.0  0.0  
8  0.0  0.0  
9  0.0  0.0  

[10 rows x 62 columns]

In [ ]:
#svm classification

In [ ]:
array=df.values
x_feature=array[:,2:]
y_label=array[:,2].astype('int')
print(x_feature.shape)
print(y_label.shape)

(2082, 60)
(2082,)


In [ ]:
import cv2
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from tqdm import tqdm

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(x_feature,y_label,test_size=0.10,random_state=7)

In [ ]:
# Normalise the data after splitting to avoid information leak between train and test set.

scaler_norm = MinMaxScaler()

X_train = scaler_norm.fit_transform(X_train)
X_test = scaler_norm.fit_transform(X_test)

In [ ]:
# Random check
model_SVC=SVC(kernel='rbf',C=100,gamma=0.001)

kfold=KFold(n_splits=10, shuffle=True)
cv_results=cross_val_score(model_SVC,X_train,Y_train,cv=kfold,scoring='accuracy')
msg="%s %f (%f)" % ('Training Accuracy: ',cv_results.mean(),cv_results.std())
print(msg)

Training Accuracy:  0.526434 (0.029042)


In [ ]:
# SVM hypertuning using GridSeachCV
model_SVC=SVC()

kfold=KFold(n_splits=10)
param_grid = {'C': [1, 10, 100, 500, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

grid=GridSearchCV(estimator=model_SVC,param_grid=param_grid,scoring='accuracy',cv=kfold,verbose=3)
grid_result=grid.fit(X_train,Y_train)

print("Best: %f using %s" % (grid_result.best_score_,grid_result.best_params_))

Fitting 10 folds for each of 25 candidates, totalling 250 fits
[CV 1/10] END .........C=1, gamma=1, kernel=rbf;, score=0.532 total time=   0.2s
[CV 2/10] END .........C=1, gamma=1, kernel=rbf;, score=0.569 total time=   0.2s
[CV 3/10] END .........C=1, gamma=1, kernel=rbf;, score=0.548 total time=   0.2s
[CV 4/10] END .........C=1, gamma=1, kernel=rbf;, score=0.636 total time=   0.3s
[CV 5/10] END .........C=1, gamma=1, kernel=rbf;, score=0.578 total time=   0.2s
[CV 6/10] END .........C=1, gamma=1, kernel=rbf;, score=0.583 total time=   0.2s
[CV 7/10] END .........C=1, gamma=1, kernel=rbf;, score=0.583 total time=   0.2s
[CV 8/10] END .........C=1, gamma=1, kernel=rbf;, score=0.556 total time=   0.3s
[CV 9/10] END .........C=1, gamma=1, kernel=rbf;, score=0.572 total time=   0.2s
[CV 10/10] END ........C=1, gamma=1, kernel=rbf;, score=0.545 total time=   0.2s
[CV 1/10] END .......C=1, gamma=0.1, kernel=rbf;, score=0.505 total time=   0.2s
[CV 2/10] END .......C=1, gamma=0.1, kernel=rb

In [ ]:
model_SVC = SVC(C=500,gamma=0.1, kernel='rbf')
model_SVC.fit(X_train,Y_train)

predictions=model_SVC.predict(X_test)

print("accuracy for svc :",accuracy_score(Y_test,predictions))
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

accuracy for svc : 0.5119617224880383
[[105   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   1   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   0   0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
          14       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         1
          20       0.50      1.00      0.67         1
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         5
          24       0.00      0.00      0.00         2
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         4
          27       0.00      0.00      0.00         2
          28       0.00      0.00      0.00         3
          29       0.07      0.17      0.10         6
          30 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
#RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
train_x,test_x,train_y,test_y = train_test_split(x_feature,y_label,test_size = 0.30)
rfc = RandomForestClassifier(n_estimators=4000,criterion='gini')
rfc = rfc.fit(train_x,train_y)
y_pred3 = rfc.predict(test_x)
print("Accuracy Score of Random Forest Classifier : ", accuracy_score(y_pred3,test_y))

Accuracy Score of Random Forest Classifier :  0.8528


In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
train_x, test_x, train_y, test_y = train_test_split(x_feature, y_label, test_size=0.30)
dtc = DecisionTreeClassifier(criterion='gini')
dtc.fit(train_x, train_y)
y_pred = dtc.predict(test_x)
accuracy = accuracy_score(test_y, y_pred)
print("Accuracy Score of Decision Tree Classifier:", accuracy)


NameError: name 'x_feature' is not defined