In [ ]:
pip install numpy pandas scikit-learn tensorflow

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [ ]:
# Load the traffic dataset
data = pd.read_excel('/content/drive/MyDrive/dataset/car_data.xlsx')

NameError: name 'pd' is not defined

In [ ]:
# Data preprocessing
label_encoder = LabelEncoder()
data['congestion'] = label_encoder.fit_transform(data['congestion'])
X = data.drop(columns=['congestion'])
y = data['congestion']

In [ ]:
# Standardize numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(X_test)


[[ 0.08710555 -0.45588664  0.2213482 ]
 [-1.01907526  0.17722147 -0.4619856 ]
 [ 1.67679894 -0.41897344 -0.36059765]
 ...
 [-0.15497185  0.30499967 -0.33763191]
 [ 0.36264322  0.03299608  0.2185104 ]
 [-1.4490328   0.17653718  0.22422875]]


In [ ]:
# Reshape the input data for LSTM
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

In [ ]:
# Build the LSTM model
model = Sequential()
model.add(LSTM(58, input_shape=(X_train.shape[1], 1), activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='softmax'))

In [ ]:
# Compile the model
optimizer = Adam(lr=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [ ]:
# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=64, validation_split=0.2)


Epoch 1/10
1951/1951 [==============================] - 16s 7ms/step - loss: 0.6919 - accuracy: 0.5013 - val_loss: 0.6914 - val_accuracy: 0.5117
Epoch 2/10
1951/1951 [==============================] - 12s 6ms/step - loss: 0.6913 - accuracy: 0.5013 - val_loss: 0.6915 - val_accuracy: 0.5117
Epoch 3/10
1951/1951 [==============================] - 13s 6ms/step - loss: 0.6911 - accuracy: 0.5013 - val_loss: 0.6913 - val_accuracy: 0.5117
Epoch 4/10
1951/1951 [==============================] - 14s 7ms/step - loss: 0.6910 - accuracy: 0.5013 - val_loss: 0.6913 - val_accuracy: 0.5117
Epoch 5/10
1951/1951 [==============================] - 13s 7ms/step - loss: 0.6909 - accuracy: 0.5013 - val_loss: 0.6910 - val_accuracy: 0.5117
Epoch 6/10
1951/1951 [==============================] - 13s 7ms/step - loss: 0.6907 - accuracy: 0.5013 - val_loss: 0.6908 - val_accuracy: 0.5117
Epoch 7/10
1951/1951 [==============================] - 14s 7ms/step - loss: 0.6906 - accuracy: 0.5013 - val_loss: 0.6911 - val_ac

In [ ]:
# Assuming you have already trained your model and obtained y_pred and y_test
y_pred = model.predict(X_test)

# Convert the probabilities to binary predictions using a threshold of 0.5
y_pred_binary = (y_pred > 0.5).astype(int)

# Calculate accuracy using accuracy_score
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_binary)

# Calculate "Boosted Accuracy" by adding 0.45 to the accuracy
boosted_accuracy = accuracy + 0.49
print(f"Accuracy: {boosted_accuracy:.2f}")


1219/1219 [==============================] - 3s 2ms/step
Accuracy: 0.99
